### ISSUE TITLE
 undefined symbol: _ZN5caffe20curandGetErrorStringE12curandStatus

### ISSUE THREAD

**Issue by Darienzhangyy** [martinkersner/train-CRF-RNN#22]
When I run the data2lmdb.py, I met with such weird error message:

 python data2lmdb.py
Traceback (most recent call last):
  File "data2lmdb.py", line 14, in <module>
    import caffe
  File "/home/ubuntu/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/ubuntu/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: /home/ubuntu/caffe/python/caffe/../../build/lib/libcaffe.so.1.0.0-rc3: undefined symbol: _ZN5caffe20curandGetErrorStringE12curandStatus

Did any one meet with such error? Thanks

**Comment by prakarshupmanyu** [comment]
I face the same problem. To overcome it I use "/usr/bin/python data2lmdb.py" instead of "python data2lmdb.py".
For some reason using Anaconda python gives this error. Make sure you install the dependencies using "/usr/bin/pip install <package>" and not "pip install <package>" if you want the above solution to work.
