### ISSUE TITLE
Error when trying data2lmdb

### ISSUE THREAD

**Issue by matthiasmace** [martinkersner/train-CRF-RNN#50]
Hi when trying to train crfasrnn with my own data, I get stuck in data preparation. I guess it could arise from malformed PNG but I do not get the solution. Any idea ?

>python2.7 data2lmdb.py
3 train images
0 test images
Train images
Traceback (most recent call last):
  File "data2lmdb.py", line 235, in <module>
    main()
  File "data2lmdb.py", line 54, in main
    convert2lmdb(path_src, train_imgs, image_ext, path_dst, class_ids, preprocess_mode, im_sz, 'image')
  File "data2lmdb.py", line 161, in convert2lmdb
    img = preprocess_image(img, preprocess_mode, im_sz)
  File "data2lmdb.py", line 167, in preprocess_image
    img = preprocess_data(img, mode, im_sz, 'image')
  File "data2lmdb.py", line 197, in preprocess_data
    img = np.pad(img, ((0, im_sz-img.shape[0]), (0, im_sz-img.shape[1]), (0,0)), 'constant', constant_values=(0))
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/arraypad.py", line 1295, in pad
    pad_width = _validate_lengths(narray, pad_width)
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/arraypad.py", line 1086, in _validate_lengths
    raise ValueError(fmt % (number_elements,))
ValueError: ((0, -100), (0, -524), (0, 0)) cannot contain negative values.

**Comment by Sam813** [comment]
your input image size is bigger than 500 x 500
